# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rs < Formula
  desc "CLI for the RenderScreenshot API"
  homepage "https://renderscreenshot.com"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.0/rs_darwin_amd64.tar.gz"
      sha256 "19877a3854ba05cb1fc9c15143fcafe9b8607603e4f93701d90530b800a7c098"

      define_method(:install) do
        bin.install "rs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.0/rs_darwin_arm64.tar.gz"
      sha256 "015b5e3784478a1c3c5d385157c53981563d9c07c2cdfdf40aa4af18850e0699"

      define_method(:install) do
        bin.install "rs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.0/rs_linux_amd64.tar.gz"
      sha256 "a462140467346a73df0cef897cd94b0d0b34e10cfd651681f40d94d898474abe"
      define_method(:install) do
        bin.install "rs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.0/rs_linux_arm64.tar.gz"
      sha256 "8667f568047bd506613b6f9fa9120ee4222e9e132fa64a16678e3bd91222a603"
      define_method(:install) do
        bin.install "rs"
      end
    end
  end
end
