# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rs < Formula
  desc "CLI for the RenderScreenshot API"
  homepage "https://renderscreenshot.com"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.2/rs_darwin_amd64.tar.gz"
      sha256 "cb09c979510cf75d797f21c566e598acc61d58803194afa504705d94a23391b3"

      define_method(:install) do
        bin.install "rs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.2/rs_darwin_arm64.tar.gz"
      sha256 "64d42df3e44b213b07e0de57388f1993ff2e10de79570236254d67deb5111886"

      define_method(:install) do
        bin.install "rs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.2/rs_linux_amd64.tar.gz"
      sha256 "529e4d94cb2156fcc1540013d954926805dbaab259759cfb15c1e713c6a9a05d"
      define_method(:install) do
        bin.install "rs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Render-Screenshot/rs-cli/releases/download/v0.1.2/rs_linux_arm64.tar.gz"
      sha256 "5e7153f519ac86be79340be0544a6c99112e73697573a1cfb6297da6492fbcf7"
      define_method(:install) do
        bin.install "rs"
      end
    end
  end
end
